library(RWeka)
library(partykit)
library(caTools)
data("iris")
View(iris)
summary(iris)
split = sample.split(iris, SplitRatio = 0.7)
dataTrain = subset(iris, split==TRUE)
dataTest = subset(iris, split==FALSE)
m1 <- J48(Species~., dataTrain)
summary(m1)
dataTestPred <- predict(m1, dataTest)
table_matrix <- table(dataTest$Species, dataTestPred)
print(table_matrix)
accuracy_Test <- sum(diag(table_matrix)) / sum(table_matrix)
cat("Test Accuracy is: ", accuracy_Test)
plot(m1, type="simple")